apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c28,c7
    openshift.io/sa.scc.supplemental-groups: 1000770000/10000
    openshift.io/sa.scc.uid-range: 1000770000/10000
    security.openshift.io/MinimallySufficientPodSecurityStandard: baseline
  creationTimestamp: "2026-07-27T06:38:53Z"
  labels:
    kubernetes.io/metadata.name: ai501
    kueue.openshift.io/managed: "true"
    name: ai501
    openshift-pipelines.tekton.dev/namespace-reconcile-version: 1.23.0
    openshift-pipelines.tekton.dev/namespace-trusted-configmaps-version: 1.23.0
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
  name: ai501
  resourceVersion: "5237495"
  uid: a519a955-14df-49a7-85d5-9ad0e6aaa4f8
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
